Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('', include('login.urls')),
    path('sell/', include('sellingform.urls')),
    path('', include('wishlist.urls')),
    path('profile/', include('myprofile.urls')),
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

description/urls.py
from django.conf.urls import url
from django.urls import path
from .views import desc, ask_question, answer_question, place_bid

app_name = 'description'

urlpatterns = [
    path('<int:id>/<str:title>', desc, name="desc"),
    path('ask/<int:id>', ask_question, name="ask"),
    path('answer/<int:item_id>/<int:id>', answer_question, name="ans"),
    path('bid', place_bid, name='place_bid'),
]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('parseData/<str:query>',views.parseData,name='parseData'),
    path('getData/',views.getData,name='getData'),
    path('parseDataAll/',views.parseDataAll,name='parseDataAll'),
    path('getDataAll/',views.getDataAll,name='getDataAll'),
    path('review/',views.review,name='review')
]

login/urls.py
from django.urls import path
from .views import login_page, signup, logout_page

app_name = 'login'

urlpatterns = [
    path('login', login_page, name='login'),
    path('signup', signup, name='signup'),
    path('logout', logout_page, name='logout'),
]

home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class SortBy(models.Model):

    class Meta:
        verbose_name_plural = 'Sort-by(s)'

    sort_by_choice = models.CharField(max_length=30)
    lastSort = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.sort_by_choice

class Review(models.Model):

    review_content = models.CharField(max_length=300)
    reviewer_username = models.CharField(max_length=300,default="")
    no = models.CharField(max_length=10,default="")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.review_content

home/forms.py
from django import forms
from .models import Review

attrs = {
    'class': 'form-control form-group' 
}

sort_by_choices = (
    ('Newest',"Newest"),
    ('Oldest', "Oldest"),
    ('Alphabetical',"Alphabetical"),
    ('Price (from lowest)',"Price (from lowest)"),
    ('Price (from highest)',"Price (from highest)"),
    ('End Date (from nearest)',"End Date (from nearest)"),
    ('End Date (from farthest)',"End Date (from farthest)")
)

class SortByForm(forms.Form):
    sort_by =  forms.ChoiceField(label='Sort by',widget=forms.Select(attrs=attrs),choices=sort_by_choices, initial="Newest")

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = [
            'review_content',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control',
                'placeholder' : 'Write your review here...'
            })

home/views.py
from django.shortcuts import render, redirect
from .forms import SortByForm
from sellingform.models import Item
from .models import SortBy
from description.models import Bid
from django.urls import reverse
from . import robot
from django.core import serializers
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.forms import AuthenticationForm
import requests
from .models import Review
from .forms import ReviewForm
import json
from django.contrib.auth.models import User

def home(request):
    if request.method == 'POST':
        form = SortByForm(request.POST)
        if form.is_valid():
            this_choice = request.POST.get('sort_by')
            create_object(this_choice)
            
            lastSortObject = SortBy.objects.last()
            get_objects = get_objects_sorted_by(this_choice)
           
            response = {
                'title' : 'Clauction',
                'form' : form,
                'loginform' : AuthenticationForm(),
                'seller' : get_objects_sorted_by(this_choice),
                'last' : lastSortObject,
                'sellorbuy' : 'Sell',
                'navlink' : reverse('sell'),
                'review_form' : ReviewForm(),
                'reviews' : Review.objects.all(),
            }
            return render(request,("home.html"),response)
    else:
        form = SortByForm()
        create_object('Newest')
        lastSortObject = SortBy.objects.last()

        robot.update_price_robot()

    response = {
        'title' : 'Clauction',
        'form' : form,
        'loginform' : AuthenticationForm(),
        'seller' : get_objects_sorted_by('Newest'),  
        'last' : lastSortObject,
        'sellorbuy' : 'Sell',
        'navlink' : reverse('sell'),
        'review_form' : ReviewForm(),
        'reviews' : Review.objects.all(),

    }
    return render(request,("home.html"),response)

def create_object(curr_choice):
    sortbyobjects = SortBy(sort_by_choice=curr_choice)
    sortbyobjects.save()

def get_objects_sorted_by(choice):
    if(choice=='Newest'):
        return Item.objects.all().order_by('-start_date')
    elif(choice=='Oldest'):
        return Item.objects.all().order_by('start_date')
    elif(choice=='Alphabetical'):
        return Item.objects.all().order_by('title')
    elif(choice=='Price (from lowest)'):
        return Item.objects.all().order_by("price")
    elif(choice=='Price (from highest)'):
        return Item.objects.all().order_by("-price")
    elif(choice=='End Date (from nearest)'):
        return Item.objects.all().order_by("end_date")
    elif(choice=='End Date (from farthest)'):
        return Item.objects.all().order_by('-end_date')

def parseData(request, query):
    queryResult = []

    for item in Item.objects.all():
        if(query.lower() in item.title.lower()):
            queryResult.append(item)

    item_list = serializers.serialize('json',queryResult)
    return HttpResponse(item_list, content_type="application/json")

def parseDataAll(request):
    item = Item.objects.all()

    item_list = serializers.serialize('json',item)
    return HttpResponse(item_list, content_type="application/json")

def getDataAll(request):
    url = 'http://clauction.herokuapp.com/parseDataAll/'

    response = requests.get(url)
    response_json = response.json()
    return JsonResponse(response_json, safe=False)

def getData(request):
    q = request.GET['q']
    url = 'http://clauction.herokuapp.com/parseData/' +  q

    response = requests.get(url)
    response_json = response.json()
    return JsonResponse(response_json, safe=False)

def review(request):
    if request.method == "POST":
        data = json.loads(request.body)
        form = ReviewForm({'review_content' : data['review_content']})
        if form.is_valid():
            banyak = Review.objects.all().count()
            #print('valid eheh')
            author = User.objects.get(username=request.session['username'])
            #print('uname: ' + author.username)
            item = form.save(commit=False)
            item.reviewer_username = author.username
            item.no = str(banyak+1)
            item.save()
            print(Review.objects.last().review_content)
            return JsonResponse({
                'review_content' : Review.objects.last().review_content,
                'author' : Review.objects.last().reviewer_username,
                'no' : str(banyak+1),
                'created_at' : Review.objects.last().created_at,
            })
        #print('askfjakfj')
        print(form.errors)

home/templates/home.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block css %}
<script src="{% static 'js/search_bar_home.js' %}"></script>
<script src="{% static 'js/review_bar_home.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/home.css' %}">
{% endblock %}

{% block content %}

<div class="home">

    <div class="fixed-bg intro-background">
        <img src="{% static 'logo-horizontal.png' %}" class="gambar-logo" />
        <div class="subtitle">
            Best place to bid.
        </div>
    </div>

    <div class="fixed-bg">
        <div class="kasihjarak"></div>
        <div class="sort">
            <div class="flex-row">
                <form id="sortbutton" action="{% url 'home:home' %}" method="POST">
                    {% csrf_token %}
                    {{ form.as_table }}
                    <button class="sort-button" type="submit" value="sort">Sort</button>
                </form>
            </div>
        </div>
        <div class="kasihjarak"></div>
        {% if seller.count %}
        <div class="form-group">
            <div class="col-sm-6 offset-sm-3">
                <input id="search" class="form-control" type="text" placeholder="Search your item here..">
            </div>
        </div>
        <div id="result">
            <div class="flex-wrap">
                {% for item in seller %}
                <a href="{% url 'description:desc' id=item.id title=item.title %}">
                    <div class="card-barang">
                        <img src="{{ item.image.url }}" width="250" height="180" class="gambar"
                            style="margin-top: 0; border-radius: 20px 20px 0px 0px;" />
                        <div class="info-barang">
                            <div style="margin: 15px;"></div>
                            <div class="judul-barang">
                            <a
                                    href="{% url 'description:desc' id=item.id title=item.title %}"><b>{{ item.title }}</b></a>
                            
                            </div>
                            <div style="margin: 10px;"></div>
                            <div class="harga-barang">
                                ${{ item.price }}
                            </div>
                            <div style="margin: 20px;"></div>
                            <hr>
                            <div style="margin: 8px;"></div>
                            <div class="item-status">
                                {{item.status}}
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        <div class="lastsort">
            <i>Last sorted by <b>{{last.sort_by_choice}}</b> order at <b>{{last.lastSort}}</b></i>
        </div>
        {% else %}
        <div class="flex-column">
            <div class="belom-ada" style="margin-bottom: 10px;">
                Place your first items here!
            </div>
             <div style="display: flex; justify-content: center;">
                <button class="btn btn-place-bid button-unhovered" id="custom_button"><a href="{% url 'sell' %}">Want to Sell?</a></button>
            </div>
        </div>
        {% endif %}

        <div class="kasihjarak"></div>
        <hr>
        <div class="kasihjarak"></div>
        <div class="review">
            <h2>What they say about Clauction..</h2>
            {% if user.is_authenticated %}
            <div class="kasihjarak"></div>
            <form action="" method="POST">
                {% csrf_token %}

                <div class="col-sm-6 offset-sm-3">
                    {% for field in review_form %}
                    {{field}}
                    {% endfor %}
                </div>

                <div style="margin: 10px;"></div>

                <button class="btn btn-place-bid button-unhovered" id="custom_button" onclick="writeContent()">
                    Submit!
                </button>
            </form>
            {% else %}
            <div style="display: flex; justify-content: center;">
                <button class="btn btn-place-bid button-unhovered" id="custom_button"><a href="{% url 'login:login' %}">Log In to write about yours!</a></button>
            </div>
            {% endif %}

            <!--
            <div id="review_result" class="flex-wrap">
                {% for review in reviews %}
                <div class="review-card">
                <h3>{{review.review_content}}</h3>
                <h4>{{review.reviewer_username}}</h4>
                </div>
                {% endfor %}
            </div>-->

            <div class="kasihjarak"></div>
            <div id="review_result">
                <div style="display: flex; justify-content: center;">
                    <div class="review-wrapper" id="truly_result">
                        {% for review in reviews %}
                        <div class="review-item">
                            <div class="review-content">
                                {{review.no}}.&nbsp;{{review.review_content}}
                            </div>
                            <div class="review-author">
                                by {{review.reviewer_username}}, <i>at {{review.created_at}}</i>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="kasihjarak"></div>
        </div>
    </div>
</div>

<script>
    $('.btn-place-bid').mouseover(function() {
        $(this).removeClass('button-unhovered');
        $(this).addClass('button-hovered')
    });
    $('.btn-place-bid').mouseleave(function() {
        $(this).removeClass('button-hovered');
        $(this).addClass('button-unhovered');
    });

    
    $(function() {
        var len_fit = 18;
        var title = $('.judul-barang a b');

        console.log('title: ' + title.html());

        var len_item_title = title.html().length;
        if(len_fit < len_item_title) {
            var size_now = parseInt(title.css("font-size"));
            var size_new = size_now * len_fit/len_item_title;

            title.css("font-size",size_new);
        }
    });
    
</script>

{% endblock %}