Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('', include('login.urls')),
    path('sell/', include('sellingform.urls')),
    path('', include('wishlist.urls')),
    path('profile/', include('myprofile.urls')),
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

description/urls.py
from django.conf.urls import url
from django.urls import path
from .views import desc, ask_question, answer_question, place_bid

app_name = 'description'

urlpatterns = [
    path('<int:id>/<str:title>', desc, name="desc"),
    path('ask/<int:id>', ask_question, name="ask"),
    path('answer/<int:item_id>/<int:id>', answer_question, name="ans"),
    path('bid', place_bid, name='place_bid'),
]

wishlist/urls.py
from . import views
from django.urls import path
from .views import add_to_wishlist, show_wishlist, parseData, getData, parseDataAll, getDataAll

app_name = 'wishlist'

urlpatterns = [
    path('add_to_wishlist/<int:id>', add_to_wishlist, name="add_to_wishlist"),
    path('my_wishlist', show_wishlist , name="show_wishlist"),
    path('parseDataWishlist/<str:query>',parseData,name='parseData'),
    path('getDataWishlist/',getData,name='getData'),
    path('parseDataAllWishlist/',parseDataAll,name='parseDataAll'),
    path('getDataAllWishlist/',getDataAll,name='getDataAll'),
]

description/models.py
from django.db import models
from sellingform.models import Item
from django.contrib.auth.models import User

class Question(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="questions")
	question = models.CharField(max_length=400, blank=False)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.question

class Answer(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
	answer = models.CharField(max_length=400, blank=False)
	time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.answer

class Bid(models.Model):
	item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="bids")
	user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="mybids")
	price = models.PositiveIntegerField(default=0)
	
	def __str__(self):
		return str(self.price)

description/forms.py
from django import forms
from .models import Bid
from django.forms import ModelForm

qn_attrs = {
        'class': 'form-control',
        'placeholder': 'message/question',
        }

ans_attrs = {
        'class': 'form-control',
        'placeholder': 'Write your reply',
        }

class QuestionForm(forms.Form):
    question = forms.CharField(label="", required=True, max_length=400, widget=forms.TextInput(attrs=qn_attrs))

class AnswerForm(forms.Form):
    answer = forms.CharField(label="", required=True, max_length=400, widget=forms.TextInput(attrs=ans_attrs))

class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ['price']
        labels = {'price':'Price'}
        widgets = {
            'price':forms.NumberInput(attrs={'class':'form-control','type':'number'}),
            }

description/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Question, Answer, Item, Bid
from .forms import QuestionForm, AnswerForm, BidForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
import datetime, requests, time

def getItem(id, title):
	url = 'http://clauction.herokuapp.com/parseData/' + title
	response = requests.get(url).json()

	#for the sake of test
	if(len(response) == 0):
		return {"model": "sellingform.item", 
            "pk": 1, 
            "fields": {"user": 1, 
            "bank_name": "BCA", 
            "bank_account": "12345678", 
            "title": "chevrolet", 
            "start_date": "2019-12-15 17:00:00+00:00", 
            "end_date": "2019-12-31 17:00:00+00:00", 
            "starting_price": 15, 
            "image": "assets/ferrari.jpg", 
            "description": "good", 
            "price": 15, 
            "status": "Available"}}
	
	for item in response:
		if item["pk"] == id:
			return item

def desc(request, id, title):
	item = getItem(id, title)["fields"]
	itemObject = Item.objects.get(id=id)

	ed_year = int(item["end_date"][0:4])
	ed_month = int(item["end_date"][5:7])
	ed_day = int(item["end_date"][8:10])
	ed_hour = int(item["end_date"][11:13])
	enddate = datetime.datetime(ed_year, ed_month, ed_day, ed_hour)
	daysleft = (enddate - datetime.datetime.now()).days
	hoursleft = (enddate - datetime.datetime.now()).seconds//3600
	countdown = str(daysleft) + " days "
	curorlast = "Current"
	onclick = ""

	if hoursleft == 1:
		countdown += str(hoursleft) + " hour"
	elif hoursleft > 1:
		countdown += str(hoursleft) + " hours"
	
	if daysleft < 0:
		countdown = "Time's Up"
		curorlast = "Final"
		onclick = "return false"

	lastbid = itemObject.bids.last()
	lastprice = lastbid
	if lastbid == None:
		lastbid = 0
		lastprice = item["starting_price"]
	
	context = {
		'qnform': QuestionForm(),
		'ansform' : AnswerForm(),
		'bidform' : BidForm(),
		'loginform': AuthenticationForm(),
        'title': "Clauction: " + item["title"],
		'navlink' : reverse('sell'),
		'sellorbuy' : 'Sell',
		'item' : itemObject,
		'countdown' : countdown,
		'oc' : onclick,
		'curorlast' : curorlast,
		'lastbid' : lastbid,
		'lastprice' : lastprice,
		'bidcount' : itemObject.bids.count,
    }
	return render(request, 'description_page.html', context)

@login_required(login_url="/login")
def ask_question(request, id):
	item = Item.objects.get(id=id)
	if request.method == "POST":
		form = QuestionForm(request.POST)
		if form.is_valid():
			Question.objects.create(
				item = item,
				question = request.POST.get('question'),
				time = request.POST.get('time'),
			)

	return redirect('description:desc', id, item.title)

@login_required(login_url="/login")
def answer_question(request, id, item_id):
	item = Item.objects.get(id=item_id)
	if request.method == "POST":
		form = AnswerForm(request.POST)
		if form.is_valid():
			Answer.objects.create(
				question = Question.objects.get(id=id),
				answer = request.POST.get('answer'),
				time = request.POST.get('time'),
			)
	return redirect('description:desc', item_id, item.title)

@login_required(login_url="/login")
def place_bid(request):
	item_id = request.POST.get('item_id')
	price = request.POST.get('price')
	item = Item.objects.get(id=str(item_id))
	if request.method == "POST":		
		form = BidForm(request.POST)
		if form.is_valid():
			Bid.objects.create(
				item = item,
				user = request.user,
				price = price,)
			time.sleep(15)
	return redirect('description:desc', item_id, item.title)

description/templates/description_page.html
{% extends 'base_layout.html' %}

{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/description.css' %}">
{% endblock %}

{% block content %}
<h1 class="center start">{{ item.title }}</h1>
<div class="flex-pc item">
    <div class="itemdiv">
        <img src="{{ item.image.url }}" alt="" id="itemimg" />
    </div>
    <div class="itemdiv">
        <p class="center">This Auction Ends in:</p>
        <p class="center" id="specialtxt">{{ countdown }}</p>
        <p class="center">{{ curorlast }} Price: <span id="specialtxt">${{ lastprice }}</span></p>
        {% if user.is_authenticated %}
        <button class="btn btn-place-bid" id="placebid">Place Bid</button>
        <a href="{% url 'wishlist:add_to_wishlist' id=item.id %}" class="btn btn-place-bid" id="wishlist">Add to Wishlist</a>
        {% else %}
        <p class="center" id="mustlogintxt">Click the Login button <br>to place your bid!</p>
        {% endif %}
        
    </div>
</div>

<div id="infodiv">
    <h3>Information</h3>
    <div id="infodivborder">
        <div class="center flex-pc">
            <div class="infoheaderdiv infoactive" onclick=infoOn(id) id="auctxt">Auction Details</div>
            <div class="infoheaderdiv" onclick=infoOn(id) id="paytxt">Payment</div>
            <div class="infoheaderdiv" onclick=infoOn(id) id="itemdesctxt">Item Description</div>
            <div class="infoheaderdiv" onclick=infoOn(id) id="additxt">Additionals</div>
        </div>
        <div>
            <p id="infocontent">
                Starting Bid: ${{ item.starting_price }}<br>
                Current Bid: ${{ lastbid }}<br>
                Start Date: {{ item.start_date }}<br>
                End Date: {{ item.end_date }}<br>
                Bid Count: {{ bidcount }}
            </p>
        </div>
    </div>

    <div id="qnamar">
        <h3>QnA</h3>
        {% if user.is_authenticated %}
        <form class="flex-pc" method="POST" action="{% url 'description:ask' id=item.id %}">
            {% csrf_token %}
            {{ qnform }}
            <button type="submit" class="btn btn-submit">Submit</button>
        </form>
        {% else %}
        <p>You must first sign in to ask questions.</p>
        {% endif %}
        <div id="qna">
            {% if item.questions.all.count %}
            {% for q in item.questions.all %}
            <p class="qnaheader">Q: {{q}}</p>
            <p class="timetxt">{{q.time}}</p>
            {% if user == item.user %}
            <p class="replytxt" id="replytxt {{q.id}}" onclick=displayForm({{q.id}})>Reply</p>
            <div class="ansform" id="ansform {{ q.id }}">
                <form class='flex' method='POST' action="{% url 'description:ans' id=q.id item_id=q.item_id %}">
                    {% csrf_token %}
                    {{ ansform }}
                    <button type="submit" class='btn btn-submit'>Submit</button>
                </form>
            </div>
            {% endif %}
            
            {% for a in q.answers.all %}
            <div class="answer">
                <p class="aheader">A: {{a}}</p c>
                <p class="timetxt">{{a.time}}</p>
            </div>
            {% endfor %}

            {% endfor %}

            {% else %}
            <p>Ask us anything!</p>
            {% endif %}
        </div>
    </div>
</div>

<div id="overlay_bidform">
    <div id="overlay_content">
        <h3 class="center">Place Your Bids Here!</h3>
        <div class="bidform">
           <form method='POST' action="{% url 'description:place_bid' %}" id="bid_form">
                {% csrf_token %}
                <input type="hidden" name="item_id" value="{{ item.id }}">
                {{ bidform }}
                <button class="btn btn-place-bid" id="bidbutton">Place Bid</button>
            </form>
        </div>
        <div id="thanks_content">
            <p>Thank you {{ user.first_name }} for bidding with us!<br>
            We will contact you soon when the auction ends.</p>
        </div>
    </div>
</div>

<script>
    function infoOn(id) {
        document.getElementsByClassName("infoactive")[0].className = "infoheaderdiv";
        document.getElementById(id).className = "infoheaderdiv infoactive";
        var info = document.getElementById("infocontent");
        info.className = "infocontentblue";
        if (id == "auctxt") {
            info.innerHTML = "Starting Bid: ${{ item.starting_price }}<br>Current Bid: ${{ lastbid }}<br>Start Date: {{ item.start_date }}<br>End Date: {{ item.end_date }}<br>Bid Count: {{ bidcount }}";
            info.className = "";
        } else if (id == "paytxt") {
            info.innerHTML = "No data regarding payment methods.";
        } else if (id == "itemdesctxt") {
            info.innerHTML = "{{ item.description }}";
            info.className = "";
        } else if (id == "additxt") {
            info.innerHTML = "No additional data";
        }
    }
</script>
<script src="{% static 'js/description.js' %}"></script>

{% endblock %}