Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('', include('login.urls')),
    path('sell/', include('sellingform.urls')),
    path('', include('wishlist.urls')),
    path('profile/', include('myprofile.urls')),
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

login/urls.py
from django.urls import path
from .views import login_page, signup, logout_page

app_name = 'login'

urlpatterns = [
    path('login', login_page, name='login'),
    path('signup', signup, name='signup'),
    path('logout', logout_page, name='logout'),
]

myprofile/urls.py
from django.urls import path
from myprofile import views

app_name = 'myprofile'

urlpatterns = [
	path('', views.view_profile, name='view_profile'),
	path('edit', views.edit_profile, name='edit_profile'),
	path('change-password', views.change_password, name='change_password'),
	#path('parseData/',views.parseData,name='parseData'),
    #path('getData/',views.getData,name='getData')
]

myprofile/models.py
from django.db import models

# Create your models here.

myprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm


class EditProfileForm(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'username',
			'email',
			'first_name',
			'last_name',
			'password'
			)

myprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from login.forms import SignupForm
from login.models import UserProfile
from .forms import EditProfileForm
from sellingform.models import Item
from description.models import Bid
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from login.models import UserProfile

from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm

from django.contrib.auth import update_session_auth_hash
from django.core import serializers
from django.http import HttpResponse, JsonResponse
import requests
import json

# from django.contrib.auth.decorators import login_required

# Create your views here.

def view_profile(request):
	args = {
		'user': request.user,
		'userdata': UserProfile.objects.get(user=request.user),
		'items' : Item.objects.filter(user=request.user),
		'bids' : Bid.objects.filter(user=request.user),
		
		}
		
	return render(request, 'profile.html', args)


def edit_profile(request):
	if request.method =="POST":
		form = EditProfileForm(request.POST, instance=request.user)

		if form.is_valid():
			form.save()
			return redirect('/')

	else:
		form = EditProfileForm(instance=request.user)
		args = {'form': form}
		return render(request, 'edit_profile.html', args)


def change_password (request):
	if request.method == 'POST':
		form = PasswordChangeForm(data=request.POST, user=request.user)

		if form.is_valid():
			form.save()
			update_session_auth_hash(request, form.user)
			return redirect('/')

		else:
			return redirect('/profile/change-password')


	else:
		form = PasswordChangeForm(user=request.user)
		args = {'form': form}
		return render(request, 'change_password.html', args)

# def parseData(request):
# 	queryResult = []

# 	for item in Item.objects.filter(user=request.user):
# 		queryResult.append(item)

# 	# for bid in Bid.objects.filter(user=request.user):
# 	# 	queryResult.append(bid)

# 	item_list = serializers.serialize('json',queryResult)
# 	return HttpResponse(item_list, content_type="application/json")

# def getData(request):
# 	url = 'http://127.0.0.1:8000/profile/parseData/' 
# 	response = requests.get(url).json()
# 	print(response)
# 	return JsonResponse(response, safe=False)

myprofile/templates/change_password.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
	crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content%}
<div class='container'>
	 <div class="container"style="font-family:livvic">
		<br><br><br><br>

		<h1 style="font-family:livvic" align="center">Change Password</h1>

      	<form method="post">
			{% csrf_token %}
      		<div class="form-group row">
        		<label class="col-sm-2 col-form-label mr-2"> {{ fields.label_tag }}</label>
        		<div class="col-sm-6">
          			{{ form.as_p}}
		 			<button type="submit" class="btn btn">Submit</button>
		</form>
        		</div>
      		</div>
	
</div>

{% endblock %}

myprofile/templates/edit_profile.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}

{% block css %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" 
	crossorigin="anonymous"/>
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}
<div class='container'>
	 <div class="container"style="font-family:livvic">
    	<br><br><br><br>

		<h1 style="font-family:livvic" align="center">Edit Profile</h1>

      <form method="post">
				{% csrf_token %}
     		 <div class="form-group row">
       			 <label class="col-sm-2 col-form-label mr-2"> {{ fields.label_tag }}</label>
       			 <div class="col-sm-6">
         			 {{ form.as_p}}
		 		<button type="submit" class="btn btn">Submit</button>
		</form>
        		</div>
     		 </div>

	
		</div>

{% endblock %}

myprofile/templates/profile.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}

{% block css%}
<script src="{% static 'js/myprofile.js' %}"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<link rel="stylesheet" type="text/css" href="{% static 'css/profile.css' %}">
{% endblock %}
{% block content %}
<br><br><br>
<div class="container bootstrap snippet">
    <div class="row">
    	<br>
    	
    </div>
    <div class="row">
  		<div class="col-sm-3"><!--left col-->
              

      <div class="text-center">
        <img src="http://ssl.gstatic.com/accounts/ui/avatar_2x.png" class="avatar img-circle img-thumbnail" alt="avatar">
        <div class="col-sm-10" style="font-family:livvic"><h2>{{user}}</h2></div>
        <!-- <h6>Upload a different photo...</h6>
        <input type="file" class="text-center center-block file-upload"> -->
      </div></hr><br>
     </div>
		<div class="row">
		 <div class="col-xs-6">
				<div class='container' style="font-family:livvic">
					
					 <div class="row">

					 	<div class="col-6 col-sm-3"><h4>Name   :</h4></div>
						  <div class="col col"><h4>{{user.first_name}} {{user.last_name}}<h4></div>

						  <!-- Force next columns to break to new line -->
						  <div class="w-100"></div>

					</div>


					 <div class="row">

					 	<div class="col-6 "><h4>Phone Number   :</h4></div>
						  <div class="col-sm-6"><h4>{{userdata.phone_number}}<h4></div>

						  <!-- Force next columns to break to new line -->
						  <div class="w-100"></div>

					</div>




					 <div class="row">

					 	<div class="col-6 col-sm-3"><h4>Address   :</h4></div>
						  <div class="col-sm-6"><h4>{{userdata.address}}<h4></div>

						  <!-- Force next columns to break to new line -->
						  <div class="w-100"></div>

					</div>

					 <!-- 	<img src="{{ user.userprofile.image }}" width="240"> -->

					 <br><br><br>
					{% if user.is_authenticated %}

					<div class="container">
						  <div class="row justify-content-md-center">
						    <div class="col col">
						      <a href="{% url 'myprofile:edit_profile' %}"><button type="button" class="btn btn-place-bid">edit profile </button> </a> 
						    </div>
						    <div class="col-md-auto">
						     <a ><button type="button" id='history' class="btn btn-place-bid">history </button></a>
						    </div>
						    <div class="col col">
						      <a href="{% url 'myprofile:change_password' %}"><button type="button" class="btn btn">ChangePassword</button></a>
						    </div>
						  </div>
					</div>				
						
					{%else%}

					<div class="container">
						  <div class="row justify-content-md-center">
						    <div class="col col-lg-5">
						      <a href="{% url 'login:signup' %}">Sign Up</a>
						  	</div>
						  </div>
					</div>	
						
					{% endif %}
				</div>
				</div>
				






</div>
</div>
<div id='result'>

</div>

{% endblock %}