Main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('', include('description.urls')),
    path('', include('login.urls')),
    path('sell/', include('sellingform.urls')),
    path('', include('wishlist.urls')),
    path('profile/', include('myprofile.urls')),
    ]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$',
        serve, {'document_root':
        settings.MEDIA_ROOT, }),
    ]

home/urls.py
from . import views
from django.urls import path

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('parseData/<str:query>',views.parseData,name='parseData'),
    path('getData/',views.getData,name='getData'),
    path('parseDataAll/',views.parseDataAll,name='parseDataAll'),
    path('getDataAll/',views.getDataAll,name='getDataAll'),
    path('review/',views.review,name='review')
]

login/urls.py
from django.urls import path
from .views import login_page, signup, logout_page

app_name = 'login'

urlpatterns = [
    path('login', login_page, name='login'),
    path('signup', signup, name='signup'),
    path('logout', logout_page, name='logout'),
]

myprofile/urls.py
from django.urls import path
from myprofile import views

app_name = 'myprofile'

urlpatterns = [
	path('', views.view_profile, name='view_profile'),
	path('edit', views.edit_profile, name='edit_profile'),
	path('change-password', views.change_password, name='change_password'),
	#path('parseData/',views.parseData,name='parseData'),
    #path('getData/',views.getData,name='getData')
]

templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="description" content="KE13 PPW Project: Clauction">
    <meta name="keywords" content="HTML,CSS">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Livvic&display=swap" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>  
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block css %}
    {% endblock %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/overlay.css' %}">
    <title>{{ title }}</title>
</head>
<body>
    <nav class="navbar fixed-top navbar-expand-lg navbar-light navbar-color">
        <a class="navbar-brand" href="{% url 'home:home' %}"><img src="{% static 'clauction-logo.png' %}" alt="Clauction" id="logoimg"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarClauction" aria-controls="navbarClauction" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarClauction">
            <div class="navbar-nav ml-auto">
                <a class="listlink" href="{% url 'home:home' %}">Home</a>
                <a class="listlink" href="{{ navlink }}">Want to {{ sellorbuy }}?</a>
                {% if user.is_authenticated %}
                <a class="listlink" href="{% url 'myprofile:view_profile' %}">My Profile</a>
                <form action="{% url 'login:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn-login">Log Out</button>
                </form>
                
                {% else %}
                <button type="submit" class="btn-login" id="login_button">Log In</button>
                {% endif %}
            </div> 
        </div>
    </nav>

	{% block content %}
    {% endblock %}
    <div id="overlay_login">
        <div id="overlay_content_login"> 
            <h2 style="display: flex; justify-content: center;">Log In</h2>
            <form class="site-form" id="login_form" action="{% url 'login:login' %}" method="POST">
                <div style="display: flex; justify-content: center;">
                    <div class="squared">
                        <div style="padding-top: 2rem;">
                            <div class="form-group">
                                {% csrf_token %}
                                {% for field in loginform %}
                                <div style="display: flex; justify-content: center;">
                                    <div class="pair">
                                        {{field.label_tag}}
                                        <div class="col-sm-12">
                                            {{field}}
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                            <div style="display: flex; justify-content: center;">
                                <div class="signup-btn">
                                    <input type="submit" value="Log In">
                                </div>
                            </div>
                            <div style="display: flex; justify-content: center; font-size: 12px; padding-top: 0.2rem;">
                                Don't have an account?&nbsp;
                                <a href="{% url 'login:signup' %}">Sign Up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div style="display: flex; justify-content: center; padding-top: 0.5rem;">
                <div class="error">
                    {{errors}}
                </div>
            </div>
            
        </div>
    </div>
    <script src="{% static 'js/login.js' %}"></script>
</body>
</html>